# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad487ac4c4c85ed228f124c3a0becd8052fb98b8540f1659e05da7a6864d032f9b876695eba28841922c469b1b4e6cd0704e8f59a9a151298daf398d21d30ad8

test:
  secret_key_base: 6b971dba2bdf141b179d05177347439167760008bfadc1598af89b2277b6173cde42839ec05d2c3906f48f2c00c21d79d1bc9300f4b2d657ff947b57db943f46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
